routes:
  - id: root-forward
    uri: /
    plugins:
      redirect:
        uri: /resource1/
        redirect_code: 302
        
  - id: resource-one
    uris:
      - /resource1 
      - /resource1/*
    upstream:
      nodes:
        "resource-one-service:80": 1
      type: roundrobin
    plugins:
      proxy-rewrite:
        regex_uri:
            - "^/resource1/?(.*)$"
            - "/$1"

  - id: resource-two
    uris:
      - /resource2 
      - /resource2/*
    upstream:
      nodes:
        "resource-two-service:80": 1
      type: roundrobin
    plugins:
      proxy-rewrite:
        regex_uri:
            - "^/resource2/?(.*)$"
            - "/$1"

  - id: resource-three
    uris:
      - /resource3 
      - /resource3/*
    upstream:
      nodes:
        "resource-three-service:80": 1
      type: roundrobin
    plugins:
      proxy-rewrite:
        regex_uri:
            - "^/resource3/?(.*)$"
            - "/$1"

#END