apisix:
  node_listen: 9080
  enable_ipv6: false

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

nginx_config:
  error_log: "/dev/stderr"
  error_log_level: "warn"
  worker_processes: "auto"

plugins:
  - openid-connect
  - authz-keycloak
  - proxy-rewrite
  - serverless-pre-function
  - serverless-post-function
  - redirect
  - syslog
  - prometheus
  - response-rewrite