version: '3.9'
services:
  api-gateway-service:
    build:
      context: ../../platform/apisix
    container_name: api_gateway_service
    environment:
      - APISIX_SESSION_SECRET=${APISIX_SESSION_SECRET}
      - KEYCLOAK_URL=http://iam-service:8080/iam
      - KEYCLOAK_CLIENT_ID=demo-APISIX
      - KEYCLOAK_CLIENT_SECRET=${APISIX_CLIENT_AUTH_SECRET}
      - KEYCLOAK_REALM=demo
      - BASE_URL=http://localhost
    volumes:
      - ../../platform/apisix/config/config.yaml:/usr/local/apisix/conf/config.yaml
      - ../../platform/apisix/config/apisix-final.yaml:/usr/local/apisix/conf/apisix.yaml
    ports:
      - "80:9080"
    depends_on:
      - iam-service
      - resource-one-service
      - resource-two-service
      - resource-three-service
  
  # IAM
  iam-service:
    build:
      context: ../../platform/keycloak
      dockerfile: Dockerfile
    container_name: iam_service
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=http://localhost/iam
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=1234
      - KC_DB=postgres
      - KC_DB_URL_HOST=iam-db-service
    volumes:
      - ../../temp/keycloak-data:/opt/keycloak/data
      - ../../iam/keycloak/themes/custom:/opt/keycloak/themes/custom
    depends_on:
      - iam-db-service

  iam-db-service:
    image: postgres:14
    container_name: iam_db_service
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=1234
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  # Resources
  resource-one-service:
    image: nginx:alpine
    volumes:
      - ../../resources/resource1:/usr/share/nginx/html
  
  resource-two-service:
    image: nginx:alpine
    volumes:
      - ../../resources/resource2:/usr/share/nginx/html

  resource-three-service:
    image: nginx:alpine
    volumes:
      - ../../resources/resource3:/usr/share/nginx/html

volumes:
  keycloak_data:

